jobs:
  - job: real_device_e2e
    pool:
      vmImage: 'macOS-10.13'
    variables:
      CI: true
      SESSION_ID: 6b153523-874e-4f86-9b6d-5a9f99d61a60 # Temporary until Sauce RDC rolls out new solution
      REAL_DEVICE: true
    steps:
    - script: java -jar jars/client.jar server --manualUrl https://us1-manual.app.testobject.com --routerUrl wss://us1.api.testobject.com/api/vusb/forward &
      displayName: Start Client
    - script: |
        java -jar jars/client.jar connect --apiKey $SAUCE_LABS_RDC_API_KEY --sessionId $SESSION_ID
        adb connect localhost:7000
      displayName: Start Remote ADB
    - script: adb devices
      displayName: List Android Devices
    - task: NodeTool@0
      inputs:
        versionSpec: 11.x
    - script: npm install
      displayName: Install Node dependencies
    - script: npm run build
      displayName: Build
    - script: npx mocha --timeout 6000000 --reporter mocha-junit-reporter --recursive build/test/functional/ -g @skip-ci -i --exit
      displayName: Run tests
