jobs:
  - job: real_device_e2e
    pool:
      vmImage: 'macOS-10.13'
    variables:
      CI: true
      SESSION_ID: 18ade986-757a-4b9d-8146-116e3c534d1a # Temporary until Sauce RDC rolls out new solution
      REAL_DEVICE: true
      MOCHA_FILE: mocha-test-results.xml
    steps:
    - script: java -jar jars/client.jar server --manualUrl https://us1-manual.app.testobject.com --routerUrl wss://us1.api.testobject.com/api/vusb/forward &
      displayName: Start vUSB Client
    - script: |
        java -jar jars/client.jar connect --apiKey $SAUCE_LABS_RDC_API_KEY --sessionId $SESSION_ID
        adb connect localhost:7000
      displayName: Start vUSB Remote Device
    - script: adb devices
      displayName: List Android Devices
    - task: NodeTool@0
      inputs:
        versionSpec: 11.x
    - script: npm install
      displayName: Install Node dependencies
    - script: npm run build
      displayName: Build
    - script: npx mocha --timeout 6000000 --reporter mocha-junit-reporter --recursive build/test/functional/commands -g @skip-ci -i --exit
      displayName: Run tests
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFiles: $(MOCHA_FILE)
